poolsar/polls/urls.py
from django.conf.urls import include, url

from views import (
    polls_index,
    polls_create,
    polls_delete,
    polls_detail,
    polls_edit,
    polls_results,
    get_chart,
    vote,
    add_choice

)

app_name = 'polls'
urlpatterns = [
    url(r'^$', polls_index, name='index'),
    url(r'^create$', polls_create, name='create'),
    url(r'^api/index/data/$', get_chart, name='api-index'),
    url(r'^(?P<slug>[\w-]+)/$', polls_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', polls_edit, name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', polls_delete, name='delete'),
    url(r'^(?P<slug>[\w-]+)/results/$', polls_results, name='results'),
    url(r'^(?P<slug>[\w-]+)/vote/$', vote, name='vote'),
    url(r'^(?P<slug>[\w-]+)/add_choice/$', add_choice, name='add-choice'),

]

poolsar/poolsar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from accounts.views import (
        login_view,
        logout_view,
        register_view,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^register/', register_view, name="register"),
    url(r'^', include('polls.urls', namespace='polls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

poolsar/polls/models.py
import datetime
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify


class Question(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    slug = models.SlugField(unique=True)
    question_text = models.CharField(max_length=200)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)


    def __unicode__(self):
        return self.question_text

    def was_published_recently(self):
        return self.timestamp >= timezone.now() - datetime.timedelta(days=1)
    was_published_recently.admin_order_field = 'timestamp'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

    def get_absolute_url(self):
        return reverse("polls:detail", kwargs={"slug": self.slug})

    def strid(self):
        return str(self.id)

class Choice(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

class Voted(models.Model):
    vote_count = models.IntegerField(default=0)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.vote_count


def create_slug(instance, new_slug=None):
    slug = slugify(instance.question_text)
    if new_slug is not None:
        slug = new_slug
    qs = Question.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug ="{}-{}".format(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_question_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_save_question_receiver, sender=Question)

poolsar/polls/forms.py
from django.forms import ModelForm, Form
from django import forms
from .models import Question, Choice

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = [
            "question_text",
        ]

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        self.fields['choice'] = forms.CharField(max_length=80)


class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = [
            "choice_text",
        ]

poolsar/polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.views import generic
from django.db.models import Q

from .forms import QuestionForm, ChoiceForm
from .models import Question, Choice, Voted
from django.contrib.auth import get_user_model

User = get_user_model

def get_chart(request):
    data = {
        'labels': [],
        'default': []
    }

    question_list = Question.objects.order_by('-timestamp')

    for question in question_list:
        labels = "labelsof{}".format(question.question_text)
        votes = "votesof{}".format(question.question_text)
        items = {}
        items[labels] = []
        items[votes] = []
        for answer in question.choice_set.order_by('-votes').all():
            items[labels].append(answer.choice_text)
        for answer in question.choice_set.order_by('-votes').all():
            votes_count = answer.voted_set.count()
            items[votes].append(answer.votes)
        taglab = "labels{}".format(question.id)
        tagdef = "default{}".format(question.id)
        data[taglab] = items[labels]
        data[tagdef] = items[votes]


    return JsonResponse(data)


@login_required
def vote(request, slug):
    # if not request.user.is_authenticated():
    #     raise Http404

    question = get_object_or_404(Question, slug=slug)
    try:
        selected_choice = question.choice_set.get(id=request.POST['choice'])

        # for choices in question.choice_set.all():
        #     if request.user in question.voters:
        #         raise Http404("You have already voted")
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        choice_vote = Voted(user=request.user, choice=selected_choice)
        choice_vote.save()
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:detail', args=(question.slug,)))


@login_required
def add_choice(request, slug):
    obj = get_object_or_404(Question, slug=slug)
    try:
        choice_text = request.POST["choicetext"]
        new_choice = Choice(question=obj, choice_text=choice_text, user=request.user)
        new_choice.save()

    except (KeyError, Question.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': obj,
            'error_message': "Question does not exists.",
        })
    else:
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:detail', args=(obj.slug,)))


def polls_index(request):
    question_list = Question.objects.order_by('-timestamp')
    query = request.GET.get("q")
    if query:
        question_list = Question.objects.filter(
                Q(question_text__icontains=query) |
                Q(choice__choice_text__icontains=query)
            ).distinct()
    title = "Pollsar"
    context = {
        'latest_question_list': question_list,
        'title': title
    }
    return render(request, "list_view.html", context)


def polls_detail(request, slug):
    obj = get_object_or_404(Question, slug=slug)
    choiceset = obj.choice_set.order_by('-votes').all()
    if request.user.is_authenticated():
        user_asked = obj.choice_set.filter(user=request.user)
        user_voted = False
        for choice in choiceset:
            if choice.voted_set.filter(user=request.user):
                user_voted = True
    else:
        user_voted = False
        user_asked = obj

    context = {
        "question": obj,
        "choiceset": choiceset,
        "user_asked": user_asked,
        "user_voted": user_voted,
    }
    return render(request, "polls/detail.html", context)


def polls_results(request, slug):
    obj = get_object_or_404(Question, slug=slug)
    context = {
        "question": obj
    }
    return render(request, "polls/results.html", context)

@login_required
def polls_create(request):
    form = QuestionForm(request.POST or None)
    if form.is_valid():
        choice = form.cleaned_data.get('choice')
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        new_choice = Choice(question=instance, choice_text=choice)
        new_choice.save()
        instance.choice = new_choice
        instance.save()
        messages.success(request, "zrobiono")
        return HttpResponseRedirect(reverse("polls:index"))
    context = {
        "form": form,
    }
    return render(request, "polls/create.html", context)


@login_required
def polls_edit(request, slug):
    obj = get_object_or_404(Question, slug=slug)
    form = QuestionForm(request.POST or None, instance=obj)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        return HttpResponseRedirect(reverse("polls:index"))
    context = {
        "question": obj,
        "form": form
    }
    return render(request, "polls/create.html", context)


@login_required
def polls_delete(request, slug):
    obj = get_object_or_404(Question, slug=slug)
    obj.delete()
    messages.success(request, "usunieto")
    return redirect("polls:index")

poolsar/polls/templates/polls/create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>ASKERE</h1>
</br>
<form method="post" action="">{% csrf_token %}
{{ form|crispy }}

<input type="submit" value="Poll it" />
</form>
</div>
{% endblock content %}

poolsar/polls/templates/polls/detail.html
{% extends 'base.html' %}

{% block head_title %}
{{ question.question_text }} | {{ block.super }}
{% endblock head_title %}

<script>

{% block jquery %}
var endpoint = "/api/index/data/"
var defaultData{{ question.strid }} = []
var labels{{ question.strid }} = [];

$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
        labels{{ question.strid }} = data.labels{{ question.strid }}
        defaultData{{ question.strid }} = data.default{{ question.strid }}
        console.log()
        setChart{{ question.strid }}()
    },
    error: function(error_data){
        console.log("error")
        console.log(error_data)

    }
})



function setChart{{ question.strid }}(){
    var ctx = document.getElementById("myChart{{ question.strid }}");
    var myChart = new Chart(ctx, {
    type: 'horizontalBar',
    data: {
        labels: labels{{ question.strid }},
        datasets: [{
            label: '# of Votes',
            data: defaultData{{ question.strid }},
            backgroundColor: [
                'rgba(139, 93, 207, 0.5)',
                'rgba(166, 132, 216, 0.5)',
                'rgba(185, 162, 220, 0.5)',
                'rgba(215, 206, 229, 0.5)',
                'rgba(215, 206, 229, 0.5)',
                'rgba(215, 206, 229, 0.5)',
                'rgba(215, 206, 229, 0.5)',
                'rgba(215, 206, 229, 0.5)',
                'rgba(215, 206, 229, 0.5)',
                'rgba(215, 206, 229, 0.5)',
            ],
            borderColor: [
                'rgba(139, 93, 207, 1)',
                'rgba(166, 132, 216, 1)',
                'rgba(185, 162, 220, 1)',
                'rgba(215, 206, 229, 1)',
                'rgba(215, 206, 229, 1)',
                'rgba(215, 206, 229, 1)',
                'rgba(215, 206, 229, 1)',
                'rgba(215, 206, 229, 1)',
                'rgba(215, 206, 229, 1)',
                'rgba(215, 206, 229, 1)'
            ],
            borderWidth: 1,
        }]
    },
    options: {
        legend: {
        display:false
    },
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                },
            }],
            xAxes: [{
                ticks: {
                    beginAtZero:true
                },
            }]
        }
    }

});
}


{% endblock %}

</script>


{% block content %}



<div class='col-sm-8 col-md-offset-2 text-center pilar'>
        <div class="col-sm-12">
        </br>
         <div class='text-center'><p>{{ question.user }} asking: </p>
            <h3>{{ question.question_text }}</h3>

            <div>
            <canvas id="myChart{{ question.strid }}" width="800" height="500"></canvas>
            </div>
        </div>

    <div class="col-sm-6 col-sm-offset-3 votedornot">

            {% if user_voted %}
            <div class="col-sm-12 votedornot">
            <span class="label label-danger">Already voted</span>
            </div>
            {% else %}
        <div class="col-sm-12">
        <div class="btn-group">
            <form action="{% url 'polls:vote' question.slug %}" method="post">
            {% csrf_token %}
            <button type="button" class="btn btn-default dropdown-toggle vote" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <span class="glyphicon glyphicon-object-align-bottom"></span> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu">
            {% for choice in choiceset %}
            <li class="text-center" style="padding: 5px;"><button type="submit" class="btn btn-light butt" name="choice" value="{{ choice.id }}">{{ choice.choice_text }}</button></li>
            {% endfor %}
             </ul>
            </form>
        </div>
        </div>

            {% endif %}

<div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button" data-action="like" data-size="large" data-show-faces="true" data-share="true"></div>
        </div>
    {% if user_asked.count < 1 and request.user.is_authenticated %}
        <div class="col-sm-6 col-sm-offset-3">
        <form action="{% url 'polls:add-choice' question.slug %}" method="post">{% csrf_token %}

            <div class="input-group">
            <input type="text" class="form-control" placeholder="your choice" name="choicetext">
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Submit</button>
            </span>
            </div>
            </form>
            </div>
    {% endif %}



<div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5">
</div>



</div>



{% endblock content %}

poolsar/polls/templates/polls/results.html
{% extends 'base.html' %}


{% block content %}

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.slug %}">Vote again?</a>

{% endblock content %}