poolsar/polls/urls.py
from django.conf.urls import include, url

from views import (
    polls_index,
    polls_create,
    polls_delete,
    polls_detail,
    polls_edit,
    polls_results,
    get_chart,
    vote,
    add_choice

)

app_name = 'polls'
urlpatterns = [
    url(r'^$', polls_index, name='index'),
    url(r'^create$', polls_create, name='create'),
    url(r'^api/index/data/$', get_chart, name='api-index'),
    url(r'^(?P<slug>[\w-]+)/$', polls_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', polls_edit, name='edit'),
    url(r'^(?P<slug>[\w-]+)/delete/$', polls_delete, name='delete'),
    url(r'^(?P<slug>[\w-]+)/results/$', polls_results, name='results'),
    url(r'^(?P<slug>[\w-]+)/vote/$', vote, name='vote'),
    url(r'^(?P<slug>[\w-]+)/add_choice/$', add_choice, name='add-choice'),

]

poolsar/poolsar/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from accounts.views import (
        login_view,
        logout_view,
        register_view,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^login/', login_view, name="login"),
    url(r'^logout/', logout_view, name="logout"),
    url(r'^register/', register_view, name="register"),
    url(r'^', include('polls.urls', namespace='polls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

poolsar/accounts/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

poolsar/accounts/forms.py
from django import forms
from django.forms import CharField
from django.contrib.auth import (
        authenticate,
        get_user_model,
        login,
        logout,
)

User = get_user_model()

class UserLoginForm(forms.Form):
    username = CharField()
    password = CharField(widget=forms.PasswordInput)

    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist.")

            if not user.check_password(password):
                raise forms.ValidationError("Incorrect password.")

            if not user.is_active:
                raise forms.ValidationError("This user is no longer active.")

        return super(UserLoginForm, self).clean()


class UserRegisterForm(forms.ModelForm):
    email = forms.EmailField(label="Email address")
    email2 = forms.EmailField(label="Confirm Email")
    password = CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = [
            "username",
            "email",
            "email2",
            "password"
        ]

    def clean_email2(self):
        email = self.cleaned_data.get("email")
        email2 = self.cleaned_data.get("email2")
        if email != email2:
            raise forms.ValidationError("Emails must match.")
        email_qs = User.objects.filter(email=email)
        if email_qs.exists():
            raise forms.ValidationError("This email has already been registered.")
        return email

poolsar/accounts/views.py
from django.contrib.auth import (
        authenticate,
        get_user_model,
        login,
        logout,
)

from django.shortcuts import render, redirect

from .forms import UserLoginForm, UserRegisterForm

# Create your views here.

def login_view(request):
    title = "Login"
    next = request.GET.get("next")
    if next:
        next = next.replace("vote/", "")
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        login(request, user)
        if next:
            return redirect(next)
        return redirect("/")
    context = {
        "form": form,
        "title": title
    }
    return render(request, "account_form.html", context)

def register_view(request):
    next = request.GET.get("next")
    if next:
        next = next.replace("vote/", "")
    title = "Register"
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        password = form.cleaned_data.get("password")
        user.set_password(password)
        user.save()
        new_user = authenticate(username=user.username, password=password)
        login(request, new_user)
        if next:
            return redirect(next)
        return redirect("/")

    context = {
        "form": form,
        "title": title
    }
    return render(request, "account_form.html", context)

def logout_view(request):
    logout(request)
    return redirect("/")

poolsar/templates/account_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='{{ title }}' />
</form>
</div>
{% endblock content %}

poolsar/templates/base.html
{% load staticfiles %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}Pollsar{% endblock head_title %}</title>


    {% include 'base/bootstrap_defaults.html' %}
    {% include 'base/js.html' %}
    {% include 'base/messages_display.html' %}
    {% include 'base/css.html' %}
    <link rel="stylesheet" href='{% static "css/base.css" %}' />
</head>


<body style="background-color: #cfc0e8">
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.11';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

<div class='container'>
    <ol class="breadcrumb nawbar">
        <li><big><b><a href="/">Pollsar</a></b></big></li>
        <li><a href="{% url 'polls:create' %}">Create a poll</a></li>

        {% if not request.user.is_authenticated %}
        <li class="pull-right"><a href="{% url 'login' %}">Login</a></li>
        <li class="pull-right"><a href="{% url 'register' %}">Register</a></li>
        {% else %}
        <li class="pull-right"><a href="{% url 'logout' %}">Logout</a></li>
        <li class="pull-right">Asker:   {{ user }}</li>
        {% endif %}
    </ol>
{% block content %}



{% endblock content %}
</div>


<script>

    $(document).ready(function(){
      {% block jquery %}{% endblock %}
    })


</script>
</body>

</html>

poolsar/templates/list_view.html
{% extends 'base.html' %}




<script>

{% block jquery %}

{% for question in latest_question_list %}
var endpoint = "api/index/data/"
var defaultData{{ question.strid }} = []
var labels{{ question.strid }} = [];

$.ajax({
    method: "GET",
    url: endpoint,
    success: function(data){
        labels{{ question.strid }} = data.labels{{ question.strid }}
        defaultData{{ question.strid }} = data.default{{ question.strid }}
        console.log()
        setChart{{ question.strid }}()
    },
    error: function(error_data){
        console.log("error")
        console.log(error_data)

    }
})



function setChart{{ question.strid }}(){
    var ctx = document.getElementById("myChart{{ question.strid }}");
    var myChart = new Chart(ctx, {
    type: 'horizontalBar',
    data: {
        labels: labels{{ question.strid }},
        datasets: [{
            label: '# of Votes',
            data: defaultData{{ question.strid }},
            backgroundColor: [
                'rgba(139, 93, 207, 0.5)',
                'rgba(166, 132, 216, 0.5)',
                'rgba(185, 162, 220, 0.5)',
                'rgba(215, 206, 229, 0.5)',
                'rgba(215, 206, 229, 0.5)',
                'rgba(215, 206, 229, 0.5)',
                'rgba(215, 206, 229, 0.5)',
                'rgba(215, 206, 229, 0.5)',
                'rgba(215, 206, 229, 0.5)',
                'rgba(215, 206, 229, 0.5)',
            ],
            borderColor: [
                'rgba(139, 93, 207, 1)',
                'rgba(166, 132, 216, 1)',
                'rgba(185, 162, 220, 1)',
                'rgba(215, 206, 229, 1)',
                'rgba(215, 206, 229, 1)',
                'rgba(215, 206, 229, 1)',
                'rgba(215, 206, 229, 1)',
                'rgba(215, 206, 229, 1)',
                'rgba(215, 206, 229, 1)',
                'rgba(215, 206, 229, 1)'
            ],
            borderWidth: 1,
        }]
    },
    options: {
        legend: {
        display:false
    },
        scales: {
            yAxes: [{
                ticks: {
                    beginAtZero:true
                },
            }],
            xAxes: [{
                ticks: {
                    beginAtZero:true
                },
            }]
        }
    }

});
}

{% endfor %}
{% endblock %}

</script>



{% block content %}




<div class='bottom-buffer row'>
    <form method="GET" action="">
        <div class="col-sm-6 col-sm-offset-3">
        <div class="input-group">
        <input class="form-control" type="text" name="q" placeholder="Searchapolla" value="{{ request.GET.q }}"/>
            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Search  <i class="fa fa-search"></i></button>
            </span>
            </div>
        </div>
    </form>
    </div>

<div class='col-sm-8 col-md-offset-2 text-center pilar'>
    {% if not latest_question_list %}
    <h3>No polls are available with this keyword.</h3>
    {% endif %}


    <div class='row'>
        <div class='col-sm-12'>
           {% for question in latest_question_list %}
            <div class='text-center'><p>{{ question.user }} asking: </p>
        <h3><a href="{{ question.get_absolute_url }}"> >> {{ question.question_text }} << </a></h3>

        </br>
            <canvas id="myChart{{ question.strid }}" width="800" height="500"></canvas>
        </br></br></br></br></br></br>
            {% endfor %}
        </div>
    </div>
</div>



</div>

{% endblock content %}